# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact from build
        uses: actions/download-artifact@v1
        with:
          name: public

      - name: list build artifact
        run: ls

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1

      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync public s3://nakhodkin.dev
